### ISSUE TITLE
타 DApp 분석 (Life Lottery)

### ISSUE THREAD

**Issue by rygh4775** [JAVACAFE-STUDY/community-rewards#10]
https://www.stateofthedapps.com/dapps/life-lottery
* 서비스 특징
* 유저 등록 및 관리 방식
* 토큰 전송 방식

**Comment by kioku714** [comment]
https://github.com/JAVACAFE-STUDY/community-rewards/wiki/Life-Lottery-%EB%B6%84%EC%84%9D
