### ISSUE TITLE
이더리움 전송 테스트

### ISSUE THREAD

**Issue by clghks** [JAVACAFE-STUDY/community-rewards#12]

**Comment by clghks** [comment]
전송 테스트 코드 

pragma solidity ^0.4.18;

contract MyContract {
    string public name;
    string public symbol;
    uint8 public decimals;

    mapping (address => uint256) public balanceOf;
    
    event Transfer(address indexed sender, address indexed from, address indexed to, uint256 value);
    event GetBalance(address indexed sender, address indexed from, uint256 value);
        
    /* Initializes contract with initial supply tokens to the creator of the contract */
    function MyToken(uint256 initialSupply, string tokenName, string tokenSymbol, uint8 decimalUnits) public {
        balanceOf[msg.sender] = initialSupply;              // Give the creator all initial tokens
        name = tokenName;                                   // Set the name for display purposes
        symbol = tokenSymbol;                               // Set the symbol for display purposes
        decimals = decimalUnits;                            // Amount of decimals for display purposes
    }
    
    function transfer(address _from, address _to, uint256 _value) public {
        /* Check if sender has balance and for overflows */
        require(balanceOf[_from] >= _value && balanceOf[_to] + _value >= balanceOf[_to]);

        /* Add and subtract new balances */
        balanceOf[_from] -= _value;
        balanceOf[_to] += _value;
        
        /* Notify anyone listening that this transfer took place */
        Transfer(msg.sender, _from, _to, _value);
    }
    
    function getBalance(address _from) public {
        GetBalance(msg.sender, _from, balanceOf[_from]);
    }
}

**Comment by rygh4775** [comment]
@clghks 간단한 코멘트와 함께 이슈 처리해주세요

**Comment by clghks** [comment]
스마트 계약을 통한 가상 시나리오 실습 코드
