### ISSUE TITLE
회원 썸네일 보여주기

### ISSUE THREAD

**Issue by rygh4775** [JAVACAFE-STUDY/community-rewards#137]
- 썸네일 미 등록시 디폴트 썸네일 사용
- 회원 이름이 노출되는 곳에 썸네일 보여주기
  - 우측 상단 헤더, 프로필, 회원 목록, 이슈 목록 등

**Comment by rygh4775** [comment]
Error: gm not found, make sure GraphicsMagick is installed and gm is available in your environment.

**Comment by rygh4775** [comment]
수정필요: issue 내역에 참여자 프로필 사진 위치 이동

**Comment by clghks** [comment]
brew install graphicsmagick

**Comment by rygh4775** [comment]
3rd 파티 없는 패키지 이용하여 썸네일 생성으로 변경

**Comment by rygh4775** [comment]
#170
