### ISSUE TITLE
Account 리스트 조회

### ISSUE THREAD

**Issue by rygh4775** [JAVACAFE-STUDY/community-rewards#15]

**Comment by kioku714** [comment]
3763868eb3c4440e2bcd5bc3b49fb847eb8b3624 완료

**Comment by rygh4775** [comment]
이슈 처리가 끝날 경우 완료 상태로만 변경 부탁드려요.
클로즈는 제가 처리하겠습니다.
(제가 이슈 관리가 어려워서요)

**Comment by kioku714** [comment]
아 넵 알겠습니다
