### ISSUE TITLE
Account에게 토큰 전송

### ISSUE THREAD

**Issue by rygh4775** [JAVACAFE-STUDY/community-rewards#19]

**Comment by rygh4775** [comment]
transfer() 구현 완료
transferFrom() 구현 필요

**Comment by rygh4775** [comment]
@clghks 이슈 내역 공유 해주세요

**Comment by clghks** [comment]
transferFrom 이슈
- A가 B에게 approve 실행 후 A가 B에게 transferFrom 하게 되면 실패 발생
    - [approve 실행 결과](https://rinkeby.etherscan.io/tx/0x73e77b59b0d8f9beefd0970aaba8e112a660648d21c33501aba36acf1503bde8) 
    - [transferFrom 실행 결과](https://rinkeby.etherscan.io/tx/0x76f711225079e5ac3b6dcfa3d6cfeff205863fad3dc6f96e1c45a1f1122a1bc5)

**Comment by rygh4775** [comment]
시나리오가 이상한데요. 아래의 시나리오가 맞지 않나요?
1. approve(B, 100) by A
A가 B에게 자신의 토큰 100을 transfer할 수 있는 권한을 준다.
2. tranferFrom(A, C, 100) by B
B가 A의 토큰 100을 C에게 transfer한다.

**Comment by clghks** [comment]
@rygh4775 제가 잘못 이해하고 있었네요 ㅠㅠ
- [A가 C에게 approve](https://rinkeby.etherscan.io/tx/0x213626e502a40fb5a9b19bb336454bb50a4184cb2b83166dea171cf8dcceb623)
- [C가 A 토큰을 B에게 전송](https://rinkeby.etherscan.io/tx/0xc3737b121c4a159d5c3adf711b6efe070c49b4606e166475583d1e54731cc219)
