### ISSUE TITLE
[BE] Geth 설치

### ISSUE THREAD

**Issue by clghks** [JAVACAFE-STUDY/community-rewards#200]
- Docker file

**Comment by clghks** [comment]
자료 조사 
- https://hub.docker.com/r/ethereum/client-go/dockerfile

**Comment by rygh4775** [comment]
Docket 스크립트 관련해서 별도의 리파지토리에서 관리되면 좋을 것 같습니다. 
community-rewards-docker 리파지토리 생성해서 공유하는거 어떨까요?

**Comment by rygh4775** [comment]
To. @clghks 
도커 파일 관리 저장소 추가
https://github.com/JAVACAFE-STUDY/community-rewards-docker
cc. @JAVACAFE-STUDY/blockchain

**Comment by clghks** [comment]
### Geth 설정 
- docker run -d --name ethereum-node -v /Users/alice/ethereum:/root \
           -p 8545:8545 -p 30303:30303 \
           ethereum/client-go --rpc --rinkeby

**Comment by rygh4775** [comment]
infura.io를 사용하는 것으로 변경 (web3-provider)
