### ISSUE TITLE
sendTransaction vs sendRawTransaction

### ISSUE THREAD

**Issue by rygh4775** [JAVACAFE-STUDY/community-rewards#21]
- 트랜잭션 처리 방식
- 트랜잭션 서명 방식

**Comment by clghks** [comment]
자료 조사 
https://medium.com/@majecty/ethereum%EC%97%90%EC%84%9C-%EC%A7%80%EA%B0%91-full-node-%EC%97%86%EC%9D%B4-%EC%93%B8-%EC%88%98-%EC%9E%88%EB%8A%94-dapp%EB%A7%8C%EB%93%A4%EA%B8%B0-8d66c88705c

**Comment by clghks** [comment]
https://github.com/ethereum/wiki/wiki/JavaScript-API

**Comment by rygh4775** [comment]
https://github.com/JAVACAFE-STUDY/community-rewards/wiki/sendTransaction-vs-sendRawTransaction
