### ISSUE TITLE
[BE] 이벤트 참여 신청 조회 API

### ISSUE THREAD

**Issue by kioku714** [JAVACAFE-STUDY/community-rewards#221]
- API 변경
- 스키마 재설계에 따른 로직 개발

**Comment by rygh4775** [comment]
@kioku714 
API 구현이 잘못되어있어 다시 Open 하였습니다.
+ HTTP method 선언이 잘못되었어, PUT->POST로 수정하였습니다.
> https://docs.google.com/document/d/188ltFzEhpHYZ0fJUuO20wMbCeFm5OTqEyItZmXEgEEQ/edit?disco=AAAAC5hzTZw
