### ISSUE TITLE
[IF] http -> https 리다이렉트 (API 서버)

### ISSUE THREAD

**Issue by kioku714** [JAVACAFE-STUDY/community-rewards#262]
node.js 에서 설정

**Comment by kioku714** [comment]
https://github.com/JAVACAFE-STUDY/community-rewards-docker/issues/12로 이동

**Comment by kioku714** [comment]
fd89c219e381590bce73f7cc35422eb64ffb8e4e docker 파일 설정 추가

**Comment by rygh4775** [comment]
해당 기능은 구현 불필요로 close 합니다
