### ISSUE TITLE
이벤트 검색시 결과 중복

### ISSUE THREAD

**Issue by rygh4775** [JAVACAFE-STUDY/community-rewards#286]
**Describe the bug**
이벤트 검색시 동일 이벤트가 중복 되는 현상

**To Reproduce**
1. 이벤트 검색 키워드에 '오픈세미나' 입력
2. 엔터

**Expected behavior**
"5월 오픈세미나 발표"가 한건만 조회되어야 함

**Screenshots**
![image](https://user-images.githubusercontent.com/1798539/60391630-ce63ee80-9b2d-11e9-91d7-061fa6415cc8.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome

**Comment by aydenden** [comment]
### 원인
- 통신이 끝나기 전 다시 사용자가 검색 요청을 할 수 있으서 결과가 중복으로 노출 됨
### 해결방안
- 통신 요청 시 input disabled, 버튼 disabled
- 통신 중인것을 나타내기 위해 검색 버튼에 progress bar 적용(참고 링크 [MaterialUI progress](https://material-ui.com/components/progress/#interactive-integration))
