### ISSUE TITLE
로그인 버튼 오작동

### ISSUE THREAD

**Issue by rygh4775** [JAVACAFE-STUDY/community-rewards#287]
**Describe the bug**
서비스 소개 페이지에서 로그인 버튼 클릭시 Github 버그 리포트 페이지로 이동

**To Reproduce**
1. 서비스 소개 페이지에서 로그인 페이지로 이동
2. 로그인 버튼 클릭
3. Github 버그 리포트 페이지 이동

**Expected behavior**
로그인 버튼 클릭시 로그인 시도가 이루어져야 함

**Screenshots**
![IMG_2500](https://user-images.githubusercontent.com/1798539/60391689-2bac6f80-9b2f-11e9-9d73-8d886b48c979.PNG)
![IMG_2501](https://user-images.githubusercontent.com/1798539/60391691-2f3ff680-9b2f-11e9-9072-1109d8a3ef59.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: iOS12.3
 - Browser: safari

**Comment by aydenden** [comment]
### 원인
- 반응형으로 작성된 랜더 사이트의 다른 요소와 다르게 footer의 링크들은 고정 사이즈로 잡혀있음
- 그러다 보니 화면이 작은 디바이스에서는 다른 요소의 위에 footer가 그려지면서 로그인 버튼 클릭 등의 이벤트를 방해함
![image](https://user-images.githubusercontent.com/10597948/60440482-e2a00c80-9c4f-11e9-928b-f15c87b2ba0e.png)
> 로그인 폼의 배경색상을 없애서 겹쳐지는 부분 확인
### 해결방안
1. footer 내 링크의 폰트 사이즈를 화면 사이즈에 맞게 가변적으로 변경하여 하단에 위치하도록 하거나
2. 화면이 작아지면 footer를 숨기는(혹은 copyright) 방향으로 진행해야 할 것 같습니다.
두 가지 중이나 혹은 더 좋은 의견 부탁드립니다.
> 2 번안이 나온 이유는 footer를 아무리 작게 만들어도 copyright도 존재하기에 하단 내용이 2줄이 되어버리고 맙니다.

![image](https://user-images.githubusercontent.com/10597948/60440644-34e12d80-9c50-11e9-83c7-8396f9898749.png)

**Comment by rygh4775** [comment]
“시작 하기”의 z-index를 올리는 방법도 제안해봅니다. 이게 가능하다면 변경사항이 제일 적을 것 같네요.

**Comment by aydenden** [comment]
z-index를 조절하는게 가장 변경사항이 적겠네요. 그 방향으로 진행하겠습니다.

**Comment by rygh4775** [comment]
네 알겠습니다
