### ISSUE TITLE
DAPP의 토큰 발행 ERC20 

### ISSUE THREAD

**Issue by rygh4775** [JAVACAFE-STUDY/community-rewards#5]
- ERC20 (이더리움 네트워크에 발생하는 토큰 표준)
- Dapp에서 토큰 발행량 설정 (무엇을 기준으로 얼마나?)
- Dapp에서 발행한 토큰을 운영하는 방식

**Comment by rygh4775** [comment]
@kioku714 리서치한 내용 위키에 정리해서 다음주에 설명 부탁드려요.

**Comment by kioku714** [comment]
@rygh4775 넵

**Comment by rygh4775** [comment]
https://github.com/JAVACAFE-STUDY/community-rewards/wiki/DAPP%EC%9D%98-%ED%86%A0%ED%81%B0-%EB%B0%9C%ED%96%89%EA%B3%BC-ERC20
