### ISSUE TITLE
이더리움 네트워크의 Account

### ISSUE THREAD

**Issue by rygh4775** [JAVACAFE-STUDY/community-rewards#6]
- Normal Account
- Contract Account
- Dapp에서는 계정 운영을 어떤 방식으로 해야하나

**Comment by rygh4775** [comment]
@clghks 리서치한 내용 위키에 정리해서 다음주에 설명 부탁드려요.

**Comment by clghks** [comment]
자료 검색 
 - Account 
https://medium.com/@yehji205/%EC%9D%B4%EB%8D%94%EB%A6%AC%EC%9B%80-%EA%B3%84%EC%A0%95-%ED%8A%B8%EB%9E%9C%EC%9E%AD%EC%85%98-%EA%B0%80%EC%8A%A4-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%EB%B8%94%EB%A1%9D-%EA%B0%80%EC%8A%A4-%ED%95%9C%EB%8F%84-89c5428078e6

**Comment by rygh4775** [comment]
https://github.com/JAVACAFE-STUDY/community-rewards/wiki/%EC%9D%B4%EB%8D%94%EB%A6%AC%EC%9B%80-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC%EC%9D%98-Account
